### ISSUE TITLE
页眉问题

### ISSUE THREAD

**Issue by jhhuang96** [TouchFishPioneer/SEU-master-thesis#2]
学校官方给的word版本上，在摘要、目录以及每一个章节的第一页上都会有页眉。但是此模板省略了这里页眉的存在，仅在每一章的第二页开始后才出现页眉。希望能够与官方word对齐，感谢作者~

参考这里 https://rwxy.seu.edu.cn/2017/0506/c17758a188753/pagem.htm
```
页眉采用下列形式（在页眉页脚的页面设置中选择“奇偶页不同”）：
偶数页：
东南大学硕士学位论文（小五号宋体居中）
奇数页：
第 * 章章题目（小五号宋体居中）
若为博士学位论文则将页眉中的“硕士”换为“博士”。
```

[东南大学硕士学位论文模板v1.1.docx](https://github.com/TouchFishPioneer/SEU-master-thesis/files/5861663/v1.1.docx)

**Comment by rqhu1995** [comment]
尝试改了一下，好像是fancyhdr默认第一页的style是plain。

在seumasterthesis.cls文件（第238行）找到下面这段代码

```
\fancypagestyle{nom} {
    \fancyhf{}
    \fancyhead[CO]{\xiaowuhao\nomname}
    \fancyhead[CE]{\xiaowuhao\universityname{}\@thesistype}
    \fancyfoot[CO,CE]{\thepage}
}
```

在这段代码之后，添加

```
\pagestyle{seustyle}
\fancypagestyle{plain} {
    \fancyhf{}
    \fancyhead[CO]{\xiaowuhao\leftmark}
    \fancyhead[CE]{\xiaowuhao\universityname{}\@thesistype}
    \fancyfoot[CO,CE]{\thepage}
}
```

![image](https://user-images.githubusercontent.com/25341632/110324494-020c5100-8051-11eb-9e89-599d1635a91b.png)

**Comment by jhhuang96** [comment]
> 
> 
> 尝试改了一下，好像是fancyhdr默认第一页的style是plain，需要人工定义，参考[这里](https://tex.stackexchange.com/questions/346730/fancyhdr-package-not-working)
> 
> 一种简单的解决方案：
> 
> 在seumasterthesis.cls文件（第238行）找到下面这段代码
> 
> ```
> \fancypagestyle{nom} {
>     \fancyhf{}
>     \fancyhead[CO]{\xiaowuhao\nomname}
>     \fancyhead[CE]{\xiaowuhao\universityname{}\@thesistype}
>     \fancyfoot[CO,CE]{\thepage}
> }
> ```
> 
> 在这段代码之后，添加
> 
> ```
> \pagestyle{seustyle}
> \fancypagestyle{plain} {
>     \fancyhf{}
>     \fancyhead[CO]{\xiaowuhao\leftmark}
>     \fancyhead[CE]{\xiaowuhao\universityname{}\@thesistype}
>     \fancyfoot[CO,CE]{\thepage}
> }
> ```
> 
> ![image](https://user-images.githubusercontent.com/25341632/110324494-020c5100-8051-11eb-9e89-599d1635a91b.png)

@rqhu1995 添加代码后，摘要部分还是有问题（中英文摘要首页没有页眉，并且偶数页却显示‘’东南大学硕士学位论文‘）；以及目录部分的偶数页也显示了‘’东南大学硕士学位论文‘。感谢大佬再次帮忙看一下如何修改呢？

**Comment by jhhuang96** [comment]
另外，模板的倒数第二页的页眉显示错误，会误用上上一章节的标题作为页眉。

![图片](https://user-images.githubusercontent.com/17799955/110753346-70375a80-8281-11eb-9f2b-574cd5450b4d.png)

**Comment by rqhu1995** [comment]
> 另外，模板的倒数第二页的页眉显示错误，会误用上上一章节的标题作为页眉。
> 
> ![图片](https://user-images.githubusercontent.com/17799955/110753346-70375a80-8281-11eb-9f2b-574cd5450b4d.png)

——————————————
抱歉刚看到。大概是abstract和resume两章是独立定义的两种环境所以不适用各个chapter统一的页眉页脚定义。
用了一种比较笨的办法，为中文摘要、英文abstract和resume分别设置了三种pagestyle。参考的步骤：
- 第一步：在上次添加plain的地方，再定义三种fancypagestyle：zhcn-abstract，en-abstract和resume，如下图：

![image](https://user-images.githubusercontent.com/25341632/111895144-9e6c2580-8a4b-11eb-9e54-416485115590.png)

可复制粘贴的文本代码（不含已经添加过的plain）：
```
\fancypagestyle{zhcn-abstract} {
    \fancyhf{}
    \fancyhead[CO]{\xiaowuhao{中文摘要}}
    \fancyhead[CE]{\xiaowuhao\universityname{}\@thesistype}
    \fancyfoot[CO,CE]{\thepage}
}

\fancypagestyle{en-abstract} {
    \fancyhf{}
    \fancyhead[CO]{Abstract}
    \fancyhead[CE]{\xiaowuhao\universityname{}\@thesistype}
    \fancyfoot[CO,CE]{\thepage}
}

\fancypagestyle{resume} {
    \fancyhf{}
    \fancyhead[CO]{\xiaowuhao{作者简介}}
    \fancyhead[CE]{\xiaowuhao\universityname{}\@thesistype}
    \fancyfoot[CO,CE]{\thepage}
}
```
这里“中文摘要”（显示在页眉上的文字），有的直接写的是“摘要”，可以根据需要改掉。
- 第二步：找到 `\renewenvironment{abstract}[1]`这一行，在`setcounter{page}{1}`之后添加`\thispagestyle{zhcn-abstract}`（红框内）

![image](https://user-images.githubusercontent.com/25341632/111895386-33235300-8a4d-11eb-9c75-d71915c51260.png)


类似地，找到`\newenvironment{englishabstract}[1]`和`\newcommand{\resume}[1]`，在最后分别加上`\thispagestyle{en-abstract}`和`\thispagestyle{resume}`，abstract和englishabstract这里注意位置，不要添加到下面的description里面去了。

![image](https://user-images.githubusercontent.com/25341632/111895309-9e205a00-8a4c-11eb-8965-6c4add9ee891.png)

![image](https://user-images.githubusercontent.com/25341632/111895330-c314cd00-8a4c-11eb-9dfd-8ca460773a22.png)

刚写完上面的内容，发现致谢那里好像又有点问题了。还是类似的方法，再定义一个acknowledgement的pagestyle（可以就直接复制resume的pagestyle粘贴在之后修改一下），然后`\newcommand{\acknowledgement} `最后添加一下，就不赘述了，看图：

![image](https://user-images.githubusercontent.com/25341632/111895650-0708d180-8a4f-11eb-8f69-b53ba6e4828a.png)

![image](https://user-images.githubusercontent.com/25341632/111895697-46cfb900-8a4f-11eb-9a27-42cb5c787e88.png)


clean之后重新编译一下，目前来看是没有问题的：

![image](https://user-images.githubusercontent.com/25341632/111895454-957c5380-8a4d-11eb-945c-3b524b7a02c9.png)

![image](https://user-images.githubusercontent.com/25341632/111895463-a331d900-8a4d-11eb-9c54-a4ce7cf3a88d.png)

![image](https://user-images.githubusercontent.com/25341632/111895702-50592100-8a4f-11eb-913e-b90be90b6ea1.png)

![image](https://user-images.githubusercontent.com/25341632/111895708-5bac4c80-8a4f-11eb-9927-c06bc9cdba3e.png)

**Comment by baobaovn** [comment]
您好，按提示添加代码后倒数第二页的页眉还是存在问题。。其他的问题都解决了，十分感谢。不知道这个倒数第二页该怎么处理。。
![QQ截图20210406214107](https://user-images.githubusercontent.com/32662250/113720080-dc8e6800-9720-11eb-8064-1705b590fd8b.png)

**Comment by rqhu1995** [comment]
> 您好，按提示添加代码后倒数第二页的页眉还是存在问题。。其他的问题都解决了，十分感谢。不知道这个倒数第二页该怎么处理。。
> ![QQ截图20210406214107](https://user-images.githubusercontent.com/32662250/113720080-dc8e6800-9720-11eb-8064-1705b590fd8b.png)

看起来，您的附录标题里的公式的引用没有找到（“式？？”里的问号）。我个人是没有附录的，所以只使用了作者原模板里的欧几里得证明和根号二无理数证明做了验证，目前看是没有问题的，奇数页页眉是“附录X 。。。”，偶数页是“东南大学硕士学位论文”。

想知道您具体说的“有问题”只是这个问号的问题吗？还是说和奇偶页相关的问题？

**Comment by baobaovn** [comment]
您好 现在是这样的情况 以我的论文为例  我的最后一部分是致谢 附录在致谢前

奇数页65页是最后的致谢 按我的理解 第66页应该就是 尾页封面

但是现在的情况是65是致谢 66是空白页 67是一个仅有页眉的空白页 页眉是致谢之前的一个附录标题 68页 才是尾页封面

不知道是不是我操作的问题。。

![QQ截图20210407123605](https://user-images.githubusercontent.com/32662250/113810925-d7233300-979d-11eb-9544-4f8e0cd85e72.png)
![QQ截图20210407123651](https://user-images.githubusercontent.com/32662250/113810989-f1f5a780-979d-11eb-9aad-ebd6852951d9.png)

**Comment by rqhu1995** [comment]
> 您好 现在是这样的情况 以我的论文为例 我的最后一部分是致谢 附录在致谢前
> 
> 奇数页65页是最后的致谢 按我的理解 第66页应该就是 尾页封面
> 
> 但是现在的情况是65是致谢 66是空白页 67是一个仅有页眉的空白页 页眉是致谢之前的一个附录标题 68页 才是尾页封面
> 
> 不知道是不是我操作的问题。。
> 
> ![QQ截图20210407123605](https://user-images.githubusercontent.com/32662250/113810925-d7233300-979d-11eb-9544-4f8e0cd85e72.png)
> ![QQ截图20210407123651](https://user-images.githubusercontent.com/32662250/113810989-f1f5a780-979d-11eb-9aad-ebd6852951d9.png)

首先，作者的latex模板的``main.tex``中给出了全文的顺序，先是各主要章节，之后依次为：致谢、参考文献、附录、作者简介；
![image](https://user-images.githubusercontent.com/25341632/113819936-9aab0380-97ac-11eb-9b41-5a2c50699110.png)

该顺序和[东南大学硕士学位论文模板v1.1.docx](https://github.com/TouchFishPioneer/SEU-master-thesis/files/5861663/v1.1.docx)中的要求是一致的，在该文档的13页的6.2中注明了：

![image](https://user-images.githubusercontent.com/25341632/113820092-d514a080-97ac-11eb-822b-098a13899dac.png)

所以我觉得你说的**最后一部分是致谢 附录在致谢前**好像不太符合这个要求。如果默认按照这个顺序，即上面`main.tex`文件中的代码不变动的话，我这里编译出来的是没有问题的（35页开始是致谢，尾页在左下角，可以看到“止于至善”几个字，页眉是没问题的）：

![image](https://user-images.githubusercontent.com/25341632/113821115-3ee17a00-97ae-11eb-8f36-ce3d8bbd2230.png)

另外，我尝试移动位置，把致谢放在最后，附录放在致谢前，也就是参考文献、作者简介（这部分您没有说你放在哪里了，我就放在附录前了）、附录、致谢，`main.tex`的顺序：

![image](https://user-images.githubusercontent.com/25341632/113821395-9f70b700-97ae-11eb-8a9e-45afd99a85b1.png)

再次编译之后，还是没还是没能复现您的问题：

![image](https://user-images.githubusercontent.com/25341632/113821581-de067180-97ae-11eb-9811-810386acfb1c.png)

**Comment by baobaovn** [comment]
感谢您的耐心回复！那应该是我自己的操作问题了 我再仔细排查一下

**Comment by jinyouzhi** [comment]
> 您好 现在是这样的情况 以我的论文为例 我的最后一部分是致谢 附录在致谢前
> 
> 奇数页65页是最后的致谢 按我的理解 第66页应该就是 尾页封面
> 
> 但是现在的情况是65是致谢 66是空白页 67是一个仅有页眉的空白页 页眉是致谢之前的一个附录标题 68页 才是尾页封面
> 
> 不知道是不是我操作的问题。。
> 
> ![QQ截图20210407123605](https://user-images.githubusercontent.com/32662250/113810925-d7233300-979d-11eb-9544-4f8e0cd85e72.png)
> ![QQ截图20210407123651](https://user-images.githubusercontent.com/32662250/113810989-f1f5a780-979d-11eb-9aad-ebd6852951d9.png)

我也出现了与您的相似的问题，神来一笔注释了这两行后修好了。
![image](https://user-images.githubusercontent.com/13817444/126073991-2f8d5f1d-741a-404c-b80f-c4c354bd7772.png)

**Comment by LiyangHu97** [comment]
> 您好，按提示添加代码后倒数第二页的页眉还是存在问题。。其他的问题都解决了，十分感谢。不知道这个倒数第二页该怎么处理。。 ![QQ截图20210406214107](https://user-images.githubusercontent.com/32662250/113720080-dc8e6800-9720-11eb-8064-1705b590fd8b.png)

您好，我目前也遇到了这个问题，请问有什么解决方案吗
